2022-04-08 16:55:48,703 - INFO - 
Config:
'add_train': False
'batch_size': 64
'clean_data_path': None
'cur_time': '2022_04_08_16_55_47'
'data_path': './data/'
'do_continue_train': True
'do_figure_save': True
'do_log_print_to_screen': True
'do_log_save_to_file': True
'do_predict': True
'do_train': True
'do_train_visualized': False
'dropout_rate': 0
'epoch': 20
'feature_columns': [1, 3, 6]
'figure_save_path': './figure/'
'frame': 'pytorch'
'hidden_size': 64
'input_size': 3
'label_columns': [1]
'learning_rate': 0.01
'load_logger': <bound method Config.load_logger of <path_config.Config object at 0x0000018E7BC29F70>>
'log_save_path': './log/2022_04_08_16_55_47_pytorch/'
'lstm_layers': 1
'mean': None
'model_name': '_20220408.pth'
'model_postfix': {'pytorch': '.pth'}
'model_save_path': './checkpoint/'
'out_size': 1
'patience': 5
'predict_day': 1
'random_seed': 42
'read_data_path': None
'seq': None
'shuffle_train_data': False
'std': None
'stock_date': None
'stock_name': None
'test_data': None
'time_step': 30
'train_data_rate': 0.95
'train_loss_path': './train_loss'
'url_path': './data/url.csv'
'use_cuda': True
'valid_ac_path': './valid_ac'
'valid_data_rate': 0.15
'valid_loss_path': './valid_loss'
2022-04-08 16:55:57,282 - INFO - Epoch  1/20
2022-04-08 16:55:58,364 - ERROR - Run Error
Traceback (most recent call last):
  File "e:\StockCalculate\main.py", line 167, in main
    train_loss, valid_loss, valid_ac=train(self.cfig, logger, [train_data, test_data])
  File "e:\StockCalculate\model\m_pytorch.py", line 125, in train
    loss = criterion(pred_Y, _valid_Y)
UnboundLocalError: local variable '_valid_Y' referenced before assignment
